language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.8"

stages:
  - linting

jobs:
  include:
    - stage: linting
      name: "pre-commit"
      python: "3.8"
      install: pip install pre-commit
      script: pre-commit run --all --show-diff-on-failure --verbose --color always

notifications:
  slack: fodoesdoitauabc:W9UCLJUleEkUCgLEDZesVfhy
